### ISSUE TITLE
Immutable.List(...).traverse is not a function

### ISSUE THREAD

**Issue by chrisui** [salesforce-ux/gulp-theo#2]
After installing the most recent version of `gulp-theo` we receive the following error when running the defined task:

```
(node:57669) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): TypeError in plugin 'gulp-theo'
Message:
    Immutable.List(...).traverse is not a function
```

**Comment by aputinski** [comment]
I just published gulp-theo@1.0.0-beta.1 Please let me know if a fresh install fixes the issue.

**Comment by chrisui** [comment]
Resolved. Thanks @aputinski!

**Comment by chrisui** [comment]
Jumped the gun sadly here. See https://github.com/salesforce-ux/theo/issues/127
